import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Home } from '../../core/models/News';

@Injectable({
  providedIn: 'root',
})
export class mockHomeService {
  private mockHome: Home = {
    message: '',
    data: {
      home: [
        {
          id: 52,
          name: 'Cidade',
          note: null,
          is_active: 1,
          order: 1,
          _lft: 61,
          _rgt: 62,
          parent_id: null,
          created_at: '2022-12-19T17:41:37.000000Z',
          updated_at: '2023-02-09T12:15:10.000000Z',
          site_id: 13,
          is_home: 1,
          order_home: 1,
          class: 'A',
          code: '1',
          home_start: 0,
          position: 'C',
          contents: [
            {
              id: 116,
              type: 6,
              position: 1,
              image:
                'http://localhost:8080/storage/contents/NwcGQCWnIEMGDdAysl5Y8CnAiiufi1BwuSpSoUBF.jpg',
              title:
                'O Brasil ainda precisa de muito Estado antes de ser liberal de verdade',
              descritive:
                '<div itemprop="articleBody" style="outline: none; margin: 0px; padding: 0px; color: rgb(64, 64, 64); font-family: Barlow; font-size: 18px; letter-spacing: 0.18px;"><p style="outline: none; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px; text-align: justify;">Existe um mito muito perigoso, principalmente em países pobres, que é o da meritocracia. A definição estrita do conceito, segundo a Wikipédia é: “Meritocracia é uma palavra formada por&nbsp;<em style="outline: none; font-weight: inherit;">mereo</em>&nbsp;(ser digno, merecedor) e o sufixo grego&nbsp;<em style="outline: none; font-weight: inherit;">kratos&nbsp;</em>(poder, força)”. Traduzindo, trata-se do alcance do poder pelo merecimento. Segundo esta linha de pensamento, os objetivos são atingidos por aqueles que se dedicam e se esforçam em medida suficiente.</p><p style="outline: none; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 15px 0px 0px; text-align: justify;">Meritocracia pressupõe um mínimo de igualdade nas condições iniciais. Vamos pensar no Brasil. Segundo o professor Naercio Menezes, atualmente, 20 milhões de jovens, entre 18 e 24 anos, estão entrando no mercado de trabalho, dentre os quais 6 milhões não completaram o ensino médio e 4 milhões já se formaram, mas sem qualificações mínimas para arranjar emprego.&nbsp;</p><p style="outline: none; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 15px 0px 0px; text-align: justify;">Em uma pesquisa realizada no Ceará, quase 20% das crianças têm algum problema de atraso no desenvolvimento, a imensa maioria entre os mais pobres. Problemas esses que podem ser cognitivos, de desenvolvimento pessoal e de relação interpessoal. O importante é notar que, nestes casos, nem levamos em conta a qualidade do ensino, a criança pobre já chega em desvantagem já no início do período escolar.</p><p style="outline: none; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 15px 0px 0px; text-align: justify;">A partir daí, as coisas só pioram, enquanto o filho de uma pessoa mais rica estuda em escolas bilíngues, com atividades lúdicas, professores de primeira linha bem remunerados e cheia de recursos tecnológicos, o filho do mais pobre, além de estudar em escolas depauperadas, com professores desmotivados e mal pagos, ainda precisa ajudar no sustento da família, trabalhando paralelamente.</p><p style="outline: none; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 15px 0px 0px; text-align: justify;">Imagine que, após todo um processo cruelmente desigual, todos os estudantes, das classes mais altas às mais baixas, tenham de disputar a mesma vaga de emprego. Neste momento, surge a bruta narrativa meritocrática: “Quem se ‘esforça’ consegue qualquer coisa”, sempre acompanhada, para ilustrar, do exemplo solitário (e feliz) do “filho do catador de latinhas que passou em Medicina”– um modelo anedótico com poder de ciência.</p><p style="outline: none; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 15px 0px 0px; text-align: justify;">Nada pode ser mais impreciso e perverso do que jogar nos ombros daquele que foi, desde o início, abandonado pelo Estado o peso de vencer pelas próprias forças. Costumamos chamar quem defende este tipo de abordagem de “liberal de quermesse”, pois conta com pouca visão científica e pouca sensibilidade social.&nbsp;</p><p style="outline: none; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 15px 0px 0px; text-align: justify;">Como o próprio professor Menezes destaca: “O grande desafio é desenhar e implementar programas baratos e eficientes que funcionem em escala”. O Estado é essencial para diminuir esta diferença e tornar a meritocracia possível. E estamos muito longe disso.</p><p style="outline: none; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 15px 0px 0px; text-align: justify;">Até lá, é necessário um Estado forte que cuide de vários temas esquecidos no Brasil: primeira infância, a fim de se combater a perda cognitiva nas crianças mais pobres; programas de transferência de renda em grande escala, permitindo que essa criança estude sem precisar trabalhar, mantendo-se, obviamente, a sustentabilidade fiscal; e qualidade da escola pública, o&nbsp;<em style="outline: none; font-weight: inherit;">gran finale</em>&nbsp;que dará condições para o aluno se estabelecer no futuro.</p><p style="outline: none; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 15px 0px 0px; text-align: justify;">E como fazer isso sem punir o fiscal? Simples, exercendo prioridades. Do que precisamos: subsídios a um determinado setor, vantagens fiscais e proteção a um grupo específico ou um exemplar programa educacional de longo prazo?&nbsp;</p><p style="outline: none; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 15px 0px 0px; text-align: justify;">A pergunta está posta. Só após evoluirmos que poderemos renunciar ao Estado. Até lá, é só discurso vazio.</p><div><br></div></div>',
              attachment: null,
              model: null,
              url: null,
              status: 'P',
              open: 'N',
              start_date: '2023-01-17',
              end_date: '2023-12-31',
              tags: null,
              bond: null,
              credits: 'Redação',
              note: null,
              published_at: '2023-01-17 11:17:00',
              slug: 'o-brasil-ainda-precisa-de-muito-estado-antes-de-ser-liberal-de-verdade-2',
              subtitle:
                'Neste artigo, o especialista comenta sobre o discurso da meritocracia, tendo em vista a realidade pela qual o Brasil ain',
              created_at: '2023-01-17T14:18:11.000000Z',
              updated_at: '2023-02-09T12:52:41.000000Z',
              site_id: 13,
              code: null,
              page_id: 52,
              emphasis: 1,
              size_images_id: null,
              endpoint: null,
            },
            {
              id: 91,
              type: 1,
              position: 1,
              image: 'http://localhost:8080/storage/noimage.png',
              title:
                'Banco Mundial projeta crescimento de 1,3% para América Latina e Caribe em 2023',
              descritive:
                '<p dir="ltr" style="margin-top: 0pt; margin-bottom: 0pt; line-height: 1.38;"><span style="font-size: 11pt; font-family: Arial; color: rgb(0, 0, 0); background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">O Fórum Econômico Mundial publicou relatório, no qual destaca riscos globais deste ano. Entre eles estão uma eventual piora da economia, com aumento no custo de vida, um “hiato” nas medidas para conter as mudanças climáticas e a polarização social.</span></p><p><span id="docs-internal-guid-7fa6a6c9-7fff-f710-e36c-585d48e3a03b"><br></span></p><p dir="ltr" style="margin-top: 0pt; margin-bottom: 0pt; line-height: 1.38;"><span style="font-size: 11pt; font-family: Arial; color: rgb(0, 0, 0); background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">A entidade elaborou uma lista de riscos no curto e no longo prazos. No horizonte de dois anos, são mencionados uma eventual crise pela alta no custo de vida, em quadro de inflação global mais elevada, desastres naturais e eventos extremos no clima, confrontos geoeconômicos e o fracasso em mitigar mudanças climáticas.</span></p><p><br></p><p dir="ltr" style="margin-top: 0pt; margin-bottom: 0pt; line-height: 1.38;"><span style="font-size: 11pt; font-family: Arial; color: rgb(0, 0, 0); background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">São citados ainda neste cenário de mais curto prazo a erosão da coesão social e a polarização da sociedade, incidentes com danos em larga escala no meio ambiente, o fracasso na adaptação a mudanças climáticas, a disseminação de crimes no mundo cibernético e a piora da segurança nesse ambiente, além de crises de recursos naturais e a imigração voluntária em larga escala.</span></p><p><br></p><p dir="ltr" style="margin-top: 0pt; margin-bottom: 0pt; line-height: 1.38;"><span style="font-size: 11pt; font-family: Arial; color: rgb(0, 0, 0); background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">No horizonte de dez anos, são mencionados, entre outros, o risco de fracasso para mitigar as mudanças climáticas e se adaptar a elas, desastres naturais, perda de biodiversidade; imigração em larga escala involuntária e crises em recursos naturais, entre outros.</span></p><p><br></p><p dir="ltr" style="margin-top: 0pt; margin-bottom: 0pt; line-height: 1.38;"><span style="font-size: 11pt; font-family: Arial; color: rgb(0, 0, 0); background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">O Fórum Econômico Mundial adverte para o risco de “policrises”, definidas como um conjunto de riscos globais relacionados e que se mesclam, com o impacto total superando a soma de cada parte. Nesse contexto, defende uma abordagem estruturada para identificar futuros potenciais do tipo e se preparar para mitigar esses problemas. Também destaca a importância da cooperação a fim de se reforçar mais o preparo para lidar com riscos globais.</span></p>',
              attachment: null,
              model: null,
              url: null,
              status: 'P',
              open: 'N',
              start_date: '2023-01-17',
              end_date: '2028-11-23',
              tags: null,
              bond: null,
              credits: 'Adm teste',
              note: null,
              published_at: '2023-01-16 17:34:09',
              slug: 'banco-mundial-projeta-crescimento-de-13-para-america-latina-e-caribe-em-2024',
              subtitle:
                'Para a Zona do Euro, instituição prevê estagnação da atividade econômica em 2023',
              created_at: '2023-01-16T13:33:48.000000Z',
              updated_at: '2023-01-17T21:36:10.000000Z',
              site_id: 13,
              code: null,
              page_id: 52,
              emphasis: null,
              size_images_id: null,
              endpoint: null,
            },
            {
              id: 92,
              type: 1,
              position: 1,
              image:
                'http://localhost:8080/storage/contents/X7FknYF9kMOeIHWHENq3bfPiOazgvCo3GHzXGnJt.jpg',
              title:
                'China revisa o crescimento do PIB em 2021 de 8,1% para 8,4%',
              descritive:
                '<p dir="ltr" style="margin-top: 0pt; margin-bottom: 0pt; line-height: 1.38;"><span style="font-size: 11pt; font-family: Arial; color: rgb(0, 0, 0); background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">O Fórum Econômico Mundial publicou relatório, no qual destaca riscos globais deste ano. Entre eles estão uma eventual piora da economia, com aumento no custo de vida, um “hiato” nas medidas para conter as mudanças climáticas e a polarização social.</span></p><p><span id="docs-internal-guid-2ed82766-7fff-7abd-5b3e-c001b703e4a3"><br></span></p><p dir="ltr" style="margin-top: 0pt; margin-bottom: 0pt; line-height: 1.38;"><span style="font-size: 11pt; font-family: Arial; color: rgb(0, 0, 0); background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">A entidade elaborou uma lista de riscos no curto e no longo prazos. No horizonte de dois anos, são mencionados uma eventual crise pela alta no custo de vida, em quadro de inflação global mais elevada, desastres naturais e eventos extremos no clima, confrontos geoeconômicos e o fracasso em mitigar mudanças climáticas.</span></p><p><br></p><p dir="ltr" style="margin-top: 0pt; margin-bottom: 0pt; line-height: 1.38;"><span style="font-size: 11pt; font-family: Arial; color: rgb(0, 0, 0); background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">São citados ainda neste cenário de mais curto prazo a erosão da coesão social e a polarização da sociedade, incidentes com danos em larga escala no meio ambiente, o fracasso na adaptação a mudanças climáticas, a disseminação de crimes no mundo cibernético e a piora da segurança nesse ambiente, além de crises de recursos naturais e a imigração voluntária em larga escala.</span></p><p><br></p><p dir="ltr" style="margin-top: 0pt; margin-bottom: 0pt; line-height: 1.38;"><span style="font-size: 11pt; font-family: Arial; color: rgb(0, 0, 0); background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">No horizonte de dez anos, são mencionados, entre outros, o risco de fracasso para mitigar as mudanças climáticas e se adaptar a elas, desastres naturais, perda de biodiversidade; imigração em larga escala involuntária e crises em recursos naturais, entre outros.</span></p><p><br></p><p dir="ltr" style="margin-top: 0pt; margin-bottom: 0pt; line-height: 1.38;"><span style="font-size: 11pt; font-family: Arial; color: rgb(0, 0, 0); background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">O Fórum Econômico Mundial adverte para o risco de “policrises”, definidas como um conjunto de riscos globais relacionados e que se mesclam, com o impacto total superando a soma de cada parte. Nesse contexto, defende uma abordagem estruturada para identificar futuros potenciais do tipo e se preparar para mitigar esses problemas. Também destaca a importância da cooperação a fim de se reforçar mais o preparo para lidar com riscos globais.</span></p><p><br></p>',
              attachment: null,
              model: null,
              url: null,
              status: 'P',
              open: 'N',
              start_date: '2023-01-11',
              end_date: '2023-12-22',
              tags: null,
              bond: null,
              credits: 'Adm teste',
              note: null,
              published_at: '2023-01-16 10:38:00',
              slug: 'china-revisa-o-crescimento-do-pib-em-2021-de-81-para-84',
              subtitle:
                'Indústria e os serviços são os principais responsáveis pela revisão, com dados do setor agrícola quase inalterados, most',
              created_at: '2023-01-16T13:39:48.000000Z',
              updated_at: '2023-01-18T13:12:47.000000Z',
              site_id: 13,
              code: null,
              page_id: 52,
              emphasis: null,
              size_images_id: null,
              endpoint: null,
            },
          ],
        },
        {
          id: 103,
          name: 'Inicio',
          note: null,
          is_active: 1,
          order: 1,
          _lft: 95,
          _rgt: 96,
          parent_id: null,
          created_at: '2023-02-09T12:15:17.000000Z',
          updated_at: '2023-02-13T22:09:04.000000Z',
          site_id: 13,
          is_home: 1,
          order_home: 1,
          class: 'A',
          code: '10',
          home_start: 1,
          position: 'C',
          contents: [],
        },
        {
          id: 54,
          name: 'Economia',
          note: null,
          is_active: 1,
          order: 3,
          _lft: 65,
          _rgt: 66,
          parent_id: null,
          created_at: '2022-12-19T17:42:15.000000Z',
          updated_at: '2023-02-09T12:22:52.000000Z',
          site_id: 13,
          is_home: 1,
          order_home: 2,
          class: 'A',
          code: '3',
          home_start: 0,
          position: 'C',
          contents: [
            {
              id: 95,
              type: 6,
              position: 2,
              image:
                'http://localhost:8080/storage/contents/YJVcI2KFHaMDqelaiGVcoHQAvCS83M3eEtvuVNz1.jpg',
              title: 'ONS registra quinto ataque a torres de energia no Brasil',
              descritive:
                '<p>O Fórum Econômico Mundial publicou relatório, no qual destaca os riscos globais deste ano. Entre eles estão uma eventual piora da economia, com aumento no custo de vida, um “hiato” nas medidas para conter as mudanças climáticas e a polarização social.</p><p><span style="font-size: 0.875rem;">A entidade elaborou uma lista de riscos no curto e no longo prazo. No horizonte de dois anos, são mencionadas uma eventual crise pela alta no custo de vida, em quadro de proteção global mais elevada, desastres naturais e eventos extremos no clima, confrontos geoeconômicos e o fracasso em mitigar mudanças climáticas.</span><br></p><p><span style="font-size: 0.875rem;">São citados ainda neste cenário de mais curto prazo a conexão da coesão social e a polarização da sociedade, incidentes com danos em larga escala no meio ambiente, o fracasso na adaptação às mudanças climáticas, a disseminação de crimes no mundo cibernético e a piora da segurança nesse ambiente , além de crises de recursos naturais e a motivada em larga escala.</span><br></p><p><span style="font-size: 0.875rem;">No horizonte de dez anos, são mencionados, entre outros, o risco de fracasso para mitigar as mudanças climáticas e se adaptar a elas, desastres naturais, perda de biodiversidade; esboços em larga escala involuntária e crises em recursos naturais, entre outros.</span><br></p><p><span style="font-size: 0.875rem;">O Fórum Econômico Mundial adverte para o risco de “policrises”, definido como um conjunto de riscos globais relacionados e que se mesclam, com o impacto total superando a soma de cada parte. Nesse contexto, defenda uma abordagem estruturada para identificar futuros potenciais do tipo e se preparar para mitigar esses problemas. Também destaca a importância da cooperação a fim de se fortalecer mais o preparo para lidar com riscos globais.</span><br></p>',
              attachment: null,
              model: null,
              url: null,
              status: 'P',
              open: 'N',
              start_date: '2023-01-16',
              end_date: '2023-03-31',
              tags: ['amazonas1'],
              bond: null,
              credits: 'Adm teste',
              note: null,
              published_at: '2023-01-17 16:55:55',
              slug: 'ons-registra-quinto-ataque-a-torres-de-energia-no-brasil-2',
              subtitle:
                'Alexandre da Silveira disse fará reunião na terça-feira com a PF e PRF para discutir medidas de segurança',
              created_at: '2023-01-16T20:39:44.000000Z',
              updated_at: '2023-02-09T18:00:30.000000Z',
              site_id: 13,
              code: null,
              page_id: 54,
              emphasis: 0,
              size_images_id: null,
              endpoint: null,
            },
            {
              id: 117,
              type: 6,
              position: 1,
              image:
                'http://localhost:8080/storage/contents/qjx9ZXhcTuiTUIlSRjk4pjHNbo7yEKd5F23H5IyY.jpg',
              title:
                'Ministro de Minas e Energia aciona PF para investigar ataques a torres de energia pelo Brasil',
              descritive:
                '<h3><span style="color: rgb(255, 0, 0); font-family: inherit; font-size: 2.0625rem;">Testando Texto</span></h3><p>Em entrevista a jornalistas nesta terça-feira (17), o ministro de Minas e Energia, Alexandre Silveira (PSD-MG), disse que não é possível afirmar que os ataques a torres de transmissão de energia elétrica tiveram motivação política e que a Polícia Federal está com inquéritos instaurados para investigar o caso.</p><p><img style="width: 100%; float: left;" src="https://cdn.pixabay.com/photo/2018/07/31/22/08/lion-3576045__480.jpg" class="note-float-left">Em entrevista a jornalistas nesta terça-feira (17), o ministro de Minas e Energia, Alexandre Silveira (PSD-MG), disse que não é possível afirmar que os ataques a torres de transmissão de energia elétrica tiveram motivação política e que a Polícia Federal está com inquéritos instaurados para investigar o caso." data-filename="image.png" class="note-float-left"><br></p>',
              attachment: null,
              model: null,
              url: null,
              status: 'P',
              open: 'N',
              start_date: '2023-01-17',
              end_date: '2023-03-10',
              tags: null,
              bond: null,
              credits: 'Adm teste',
              note: null,
              published_at: '2023-01-17 16:39:00',
              slug: 'ministro-de-minas-e-energia-aciona-pf-para-investigar-ataques-a-torres-de-energia-pelo-brasil-2',
              subtitle:
                'Relatório aponta aumento do custo de vida e "hiato" nas medidas para conter mudanças climáticas',
              created_at: '2023-01-17T19:45:37.000000Z',
              updated_at: '2023-02-09T16:26:29.000000Z',
              site_id: 13,
              code: null,
              page_id: 54,
              emphasis: 1,
              size_images_id: null,
              endpoint: null,
            },
            {
              id: 114,
              type: 6,
              position: 1,
              image:
                'http://localhost:8080/storage/contents/jvF9F9fKrErWiwkDfA2YBzaJQQHEH0mk46v3Ri5f.jpg',
              title:
                'NSS: PL prevê pagamento de benefícios atrasados com correção do INPC',
              descritive:
                '<p style="outline: none; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px; text-align: justify; color: rgb(64, 64, 64); font-family: Barlow; font-size: 18px; letter-spacing: 0.18px;">Um novo Projeto de Lei (PL), que está em análise na Câmara dos Deputados, prevê que pagamentos atrasados pelo Instituto Nacional do Seguro Social&nbsp;<a class="classtermo" href="https://www.contabeis.com.br/previdencia/inss/" style="outline: none; color: rgb(52, 142, 157); text-decoration: none; font-weight: 700; background-image: none; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; line-height: inherit; padding: inherit; float: inherit; transition: all 0.5s ease 0s;">(INSS)</a>&nbsp;tenham uma nova forma de correção.</p><p style="outline: none; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 15px 0px 0px; text-align: justify; color: rgb(64, 64, 64); font-family: Barlow; font-size: 18px; letter-spacing: 0.18px;">O Projeto de Lei 2753/22 quer que os benefícios pagos em atraso pelo instituto sejam corrigidos pela inflação mais&nbsp;<a class="classtermo" href="https://www.contabeis.com.br/economia/juros/" style="outline: none; color: rgb(52, 142, 157); text-decoration: none; font-weight: 700; background-image: none; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; line-height: inherit; padding: inherit; float: inherit; transition: all 0.5s ease 0s;">juros</a>&nbsp;de mora.</p><p style="outline: none; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 15px 0px 0px; text-align: justify; color: rgb(64, 64, 64); font-family: Barlow; font-size: 18px; letter-spacing: 0.18px;">Segundo a proposta, as parcelas devidas deverão ser atualizadas pela variação mensal acumulada do Índice Nacional de Preços ao Consumidor (INPC). Os juros de mora, de acordo com o texto, deverão ser equivalentes àqueles cobrados dos contribuintes em atraso com o Regime Geral de Previdência Social (RGPS).</p><p style="outline: none; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 15px 0px 0px; text-align: justify; color: rgb(64, 64, 64); font-family: Barlow; font-size: 18px; letter-spacing: 0.18px;">“O projeto visa superar lacuna legal e garantir critério mais equânime e justo na atualização monetária e nos juros de mora dos benefícios previdenciários”, disse o autor da proposta, deputado Pompeo de Mattos (PDT-RS).</p><p style="outline: none; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 15px 0px 0px; text-align: justify; color: rgb(64, 64, 64); font-family: Barlow; font-size: 18px; letter-spacing: 0.18px;">O deputado lembrou que, na origem, a Lei de Benefícios da Previdência Social previa a correção dos benefícios em atraso pelo INPC, mas em 1994 esse dispositivo foi revogado. Hoje, o Regulamento da Previdência Social prevê a atualização pelo índice de reajuste dos benefícios do RGPS.</p><p style="outline: none; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 15px 0px 0px; text-align: justify; color: rgb(64, 64, 64); font-family: Barlow; font-size: 18px; letter-spacing: 0.18px;">O projeto tramita em caráter conclusivo e será analisado pelas comissões de Seguridade Social e Família; de Finanças e Tributação; e de Constituição e Justiça e de Cidadania.</p>',
              attachment: null,
              model: null,
              url: null,
              status: 'P',
              open: 'N',
              start_date: '2022-01-17',
              end_date: '2023-12-31',
              tags: null,
              bond: null,
              credits: 'Redação',
              note: null,
              published_at: '2023-01-17 11:20:31',
              slug: 'nss-pl-preve-pagamento-de-beneficios-atrasados-com-correcao-do-inpc-2',
              subtitle:
                'A Lei de Benefícios da Previdência Social previa a correção dos benefícios em atraso pelo INPC',
              created_at: '2023-01-17T14:13:00.000000Z',
              updated_at: '2023-01-17T21:36:10.000000Z',
              site_id: 13,
              code: null,
              page_id: 54,
              emphasis: null,
              size_images_id: null,
              endpoint: null,
            },
          ],
        },
        {
          id: 53,
          name: 'Política',
          note: null,
          is_active: 1,
          order: 2,
          _lft: 63,
          _rgt: 64,
          parent_id: null,
          created_at: '2022-12-19T17:42:03.000000Z',
          updated_at: '2023-02-09T12:16:07.000000Z',
          site_id: 13,
          is_home: 1,
          order_home: 3,
          class: 'A',
          code: '2',
          home_start: 0,
          position: 'C',
          contents: [
            {
              id: 128,
              type: 6,
              position: 1,
              image:
                'http://localhost:8080/storage/contents/RVfrqDxFCEzFvqKGgUuYjmNQxVqTk0Cc1M002jfO.jpg',
              title:
                'Especialistas debatem se mudanças de versões podem incriminar Marcos Do Val',
              descritive:
                '<p style="color: rgb(38, 38, 38); font-size: 18px; line-height: 28px; letter-spacing: 0.01em; font-family: &quot;CNN Sans Display&quot;, sans-serif;"><span style="font-weight: bolder;">No Painel&nbsp;CNN&nbsp;deste sábado (4), o ex-ministro da Justiça José Eduardo Cardozo e a advogada constitucionalista Samantha Meyer debateram se as mudanças de versões apresentados pelo senador&nbsp;<a href="https://www.cnnbrasil.com.br/tudo-sobre/marcos-do-val/" style="color: rgb(42, 118, 189); text-decoration: underline;">Marcos do Val (Podemos-ES)</a>&nbsp;podem incriminá-lo.</span></p><p style="color: rgb(38, 38, 38); font-size: 18px; line-height: 28px; letter-spacing: 0.01em; font-family: &quot;CNN Sans Display&quot;, sans-serif;"><span style="font-weight: bolder;">Na avaliação do ex-ministro, um parlamentar não pode “se dar ao luxo” de apresentar tantas versões diferentes a respeito de um fato. Ainda segundo ele, pode haver quebra de decoro parlamentar por parte de Do Val.</span></p><p style="color: rgb(38, 38, 38); font-size: 18px; line-height: 28px; letter-spacing: 0.01em; font-family: &quot;CNN Sans Display&quot;, sans-serif;"><span style="letter-spacing: 0.18px;">“Se o Senado não cortar na própria carne uma pessoa que age desta forma, propondo a cassação do seu mandato, ele estará fragilizado na sua legitimação perante à população”, avaliou Cardozo.</span></p>',
              attachment: null,
              model: null,
              url: null,
              status: 'P',
              open: 'N',
              start_date: '2023-02-04',
              end_date: '2030-12-04',
              tags: null,
              bond: null,
              credits: 'Copiado do CNN - Teste',
              note: null,
              published_at: '2023-02-04 20:14:00',
              slug: 'especialistas-debatem-se-mudancas-de-versoes-podem-incriminar-marcos-do-val-2',
              subtitle:
                'À CNN, o ex-ministro da Justiça José Eduardo Cardozo e a advogada constitucionalista Samantha Meyer avaliaram a situação',
              created_at: '2023-02-04T23:15:06.000000Z',
              updated_at: '2023-02-13T22:08:04.000000Z',
              site_id: 13,
              code: null,
              page_id: 53,
              emphasis: 1,
              size_images_id: null,
              endpoint: null,
            },
            {
              id: 88,
              type: 6,
              position: 2,
              image:
                'http://localhost:8080/storage/contents/sQ35tGhDxhE7vIQWQWYPwxrDBcFwkvnQ8u5soOqV.jpg',
              title:
                '8 dicas práticas para se organizar melhor trabalhando de casa',
              descritive:
                '<p>fbvfdbv</p><p>dfbvjfdbvk,fd</p><p>dfjvbkjfbvkjhdf</p><p>dsjvbfhvd</p><p>fdvbfdjhbvdl</p><p><br></p><p><br></p><p>vjnfdkjhbvfdjhvbfd</p><p>jfdbvkfdbvkjds</p>',
              attachment: null,
              model: null,
              url: 'https://www.adzuna.com.br/blog/8-dicas-praticas-para-se-organizar-melhor-trabalhando-de-casa/',
              status: 'P',
              open: 'N',
              start_date: '2023-01-06',
              end_date: '2063-11-24',
              tags: ['organização', 'home office'],
              bond: null,
              credits: 'Teste - Suporte DIX',
              note: null,
              published_at: '2023-01-17 13:55:46',
              slug: '8-dicas-praticas-para-se-organizar-melhor-trabalhando-de-casa',
              subtitle:
                'Relatório aponta aumento do custo de vida e "hiato" nas medidas para conter mudanças climáticas',
              created_at: '2023-01-16T13:22:51.000000Z',
              updated_at: '2023-01-26T17:07:04.000000Z',
              site_id: 13,
              code: null,
              page_id: 53,
              emphasis: null,
              size_images_id: null,
              endpoint: null,
            },
            {
              id: 108,
              type: 6,
              position: 1,
              image:
                'http://localhost:8080/storage/contents/EIyOfnrab1kWzH6eHISRdscNicmRMwP0JTaLMwPI.jpg',
              title:
                'Economia da China amarga um dos piores crescimentos em quase 50 anos',
              descritive:
                '<p style="font-size: 18px; line-height: 32px; color: rgb(51, 51, 51); margin-bottom: 32px; font-family: &quot;Open Sans&quot;, sans-serif;">O&nbsp;<strong style="font-weight: bold;">crescimento econômico da China em 2022</strong>&nbsp;caiu para um de seus piores níveis em quase meio século, com o quarto trimestre duramente atingido pelas&nbsp;<a href="https://noticias.r7.com/internacional/china-flexibiliza-paulatinamente-a-drastica-politica-de-covid-zero-05122022" style="text-decoration: underline; color: rgb(34, 142, 225); font-weight: bold;"><strong style="font-weight: bold;">rigorosas restrições contra a Covid-19</strong></a>&nbsp;e por uma&nbsp;<a href="https://noticias.r7.com/economia/em-meio-a-crise-da-evergrande-mais-incorporadoras-chinesas-planejam-emitir-titulos-com-garantia-05122021" style="text-decoration: underline; color: rgb(34, 142, 225); font-weight: bold;"><strong style="font-weight: bold;">queda no mercado imobiliário</strong></a>, aumentando a pressão sobre as autoridades para adotar mais estímulos este ano.</p><p style="font-size: 18px; line-height: 32px; color: rgb(51, 51, 51); margin-bottom: 32px; font-family: &quot;Open Sans&quot;, sans-serif;">Em 2022, o&nbsp;<strong style="font-weight: bold;">PIB (Produto Interno Bruto) chinês</strong>&nbsp;expandiu 3%, resultado bem aquém da meta oficial de "cerca de 5,5%" e desacelerando acentuadamente em relação ao crescimento de 8,4% em 2021. Excluindo a expansão de 2,2% após o golpe inicial da Covid em 2020, é o pior resultado desde 1976 — o último ano da Revolução Cultural de uma década que arruinou a economia local.</p><p style="font-size: 18px; line-height: 32px; color: rgb(51, 51, 51); margin-bottom: 32px; font-family: &quot;Open Sans&quot;, sans-serif;">Entre outubro e dezembro em relação ao mesmo período do ano anterior, a segunda maior economia do planeta cresceu 2,9%, seguindo os dados revelados nesta terça-feira (17) pela Agência Nacional de Estatísticas. A alta é inferior ao crescimento de 3,9% registrado no terceiro trimestre.</p><p style="font-size: 18px; line-height: 32px; color: rgb(51, 51, 51); margin-bottom: 32px; font-family: &quot;Open Sans&quot;, sans-serif;">O crescimento trimestral e alguns dos indicadores de dezembro, como as vendas no varejo, superaram as expectativas do mercado, mas os analistas observaram que o impulso econômico geral na China permaneceu fraco e destacaram os desafios enfrentados por Pequim depois que o país&nbsp;<a href="https://noticias.r7.com/internacional/china-flexibiliza-paulatinamente-a-drastica-politica-de-covid-zero-05122022" style="text-decoration: underline; color: rgb(34, 142, 225); font-weight: bold;"><strong style="font-weight: bold;">levantou abruptamente sua política de "Covid zero"</strong></a>.</p><p style="font-size: 18px; line-height: 32px; color: rgb(51, 51, 51); margin-bottom: 32px; font-family: &quot;Open Sans&quot;, sans-serif;">"Os dados de atividade em dezembro surpreenderam amplamente, mas continuam fracos, particularmente em segmentos do lado da demanda, como os gastos de varejo", disse Louise Loo, economista sênior da Oxford Economics. Ele avalia que os números sustentam a visão de que o impulso de reabertura da China “será um pouco anêmico no início, com os gastos dos consumidores sendo um dos mais atrasados nos estágios iniciais".</p>',
              attachment: null,
              model: null,
              url: null,
              status: 'P',
              open: 'N',
              start_date: '2023-01-17',
              end_date: '2023-12-31',
              tags: null,
              bond: null,
              credits: null,
              note: null,
              published_at: '2023-01-17 11:19:08',
              slug: 'economia-da-china-amarga-um-dos-piores-crescimentos-em-quase-50-anos-2',
              subtitle:
                'PIB da segunda maior economia do mundo foi afetado rigorosas restrições contra a Covid-19',
              created_at: '2023-01-17T13:55:36.000000Z',
              updated_at: '2023-01-26T20:37:23.000000Z',
              site_id: 13,
              code: null,
              page_id: 53,
              emphasis: null,
              size_images_id: null,
              endpoint: null,
            },
          ],
        },
        {
          id: 55,
          name: 'Segurança',
          note: null,
          is_active: 1,
          order: 4,
          _lft: 67,
          _rgt: 68,
          parent_id: null,
          created_at: '2022-12-19T17:42:28.000000Z',
          updated_at: '2023-02-09T12:16:24.000000Z',
          site_id: 13,
          is_home: 1,
          order_home: 3,
          class: 'A',
          code: '4',
          home_start: 0,
          position: 'C',
          contents: [
            {
              id: 137,
              type: 6,
              position: 1,
              image:
                'http://localhost:8080/storage/contents/pRfB0Vewmo4vdIEdc57Prpx6U7Xf0MFXT5bpWbrh.jpg',
              title:
                'Reabertura dos destacamentos da Polícia Militar em Tupiratins e Itapiratins visam garantia da segura',
              descritive:
                '<div class=" seguranca_edit" style="list-style: none; color: rgb(33, 37, 41); font-family: Montserrat, sans-serif; font-size: 16px;"><h3 style="list-style: none; margin-bottom: 0.5rem; line-height: 1.2; font-size: 1.75rem;">Reabertura dos destacamentos da Polícia Militar em Tupiratins e Itapiratins visam garantia da segurança pública</h3></div><div class="row" style="list-style: none; color: rgb(33, 37, 41); font-family: Montserrat, sans-serif; font-size: 16px; margin-top: -15px;"><div class="col-sm-7" style="list-style: none; width: 498.75px; flex-basis: 58.3333%; max-width: 58.3333%;"><span class="text-right font-italic" style="list-style: none; font-size: 11px;">12/02/2023 10h39 - Atualizado em 14/02/2023 10h27</span></div></div><div class="" style="list-style: none; color: rgb(33, 37, 41); font-family: Montserrat, sans-serif; font-size: 16px;"><div class="my-3 text-center" style="list-style: none;"><a href="https://www.centronortenoticias.com.br/images/noticia/A63e8ec28e6b31.jpg" class="fancybox iframe.fancybox " style="list-style: none; text-decoration: none; color: rgb(0, 0, 0) !important;"><img src="https://www.centronortenoticias.com.br/images/noticia/A63e8ec28e6b31.jpg" class="img-fluid" alt="Reabertura dos destacamentos da Polícia Militar em Tupiratins e Itapiratins visam garantia da segurança pública" style="list-style: none;"></a><figcaption style="list-style: none;"></figcaption></div></div><div style="list-style: none; color: rgb(33, 37, 41); font-family: Montserrat, sans-serif; font-size: 16px;"><p style="list-style: none; margin-bottom: 1rem; font-size: 14px;"></p><p style="list-style: none; margin-bottom: 1rem; text-align: justify;">O sábado, 11 de fevereiro, foi dia de satisfação para moradores de Tupiratins e Itapiratins, na região centro-norte do Estado, devido à reativação dos Destacamentos da Polícia Militar nas cidades, que são separadas pelo Rio Tocantins.<br style="list-style: none;"><br style="list-style: none;">As duas bases também receberam os Kits Destacamento composto por uma viatura policial, um tablet ou smartphone, um computador desktop, uma impressora térmica e um rádio portátil (HT), um tablet Mobile, um fuzil, coletes e seis pistolas.<br style="list-style: none;"><br style="list-style: none;"><span style="list-style: none; font-weight: bolder;">Cuidado com as pessoas</span><br style="list-style: none;"><br style="list-style: none;">A iniciativa do governador Wanderlei Barbosa marca o início de uma série de reativações de Bases de Destacamentos Policiais inativos, que tem como objetivo dotar todas os municípios tocantinenses de estrutura policial para combater ilícitos e garantir a segurança da população. O Governador entende que cuidar das pessoas passa necessariamente pela segurança pública.<br style="list-style: none;"><br style="list-style: none;">"Deus nos deu essa missão, que é cuidar das pessoas e fazer isso é dar segurança pra elas. As pessoas gostam e o empreendedor que vem ao Estado, a primeira coisa que observa é esse aspecto da segurança pública. Ninguém vem fazer investimento em um Estado que não tem segurança e é isso que estamos fazendo", afirmou.<br style="list-style: none;"><br style="list-style: none;">Para os gestores das cidades beneficiadas com os destacamentos, Filó Coelho (Tupiratins) e Sandro Rodrigues (Itapiratins), esses destacamentos representam o reforço da segurança para os seus municípios.<br style="list-style: none;"><br style="list-style: none;">O comandante geral da Polícia Militar, coronel Márcio Barbosa destacou o compromisso do governador com a segurança pública e que implantação das unidades de Tupiratins e Itapiratins representam a sequência do Programa TO mais Seguro. Ele lembrou que além da reativação dos destacamentos foram entregues toda a logística necessária para que os policiais posam operar são viaturas, fuzis, pistolas, coletes é outros equipamentos que os policiais precisam para oferecer segurança nos municípios.<br style="list-style: none;"><br style="list-style: none;">"Proporcionando sensação de segurança a população é o que estamos fazendo ao colocarmos policiamento ostensivo nos 139 municípios. E já conseguimos reduzir os índices de criminalidade em todo o Estado. Isso é fruto de trabalho árduo, bem planejado, que envolve os eixos de policiamento ostensivo e preventivo, policiamento de recobrimento e policiamento especializado", explicou Márcio Barbosa.<br style="list-style: none;"><br style="list-style: none;">Comandante do 3º BPM, o tenente-coronel Dernivaldo da Costa Tirello, reforçou que os militares que vão atuar em Itapiratins estarão próximos da comunidade local desenvolvendo um trabalho preventivo e, paralelamente, executarão um policiamento ostensivo de combate à criminalidade. “A comunidade ordeira pode ter certeza que a reabertura do destacamento e o reforço no policiamento diuturnamente vão permitir tranquilidade e inibir a ação de criminosos”, pontuou o oficial.<br style="list-style: none;"><br style="list-style: none;">Ao lembrar que com o novo plano operacional do PMTO, recentemente Tupiratins passou a integrar a área sob jurisdição do 7º BPM, o comandante da unidade, tenente-coronel Márcio Antônio Rodrigues de Carvalho, assegurou que a meta é assegurar a paz social e a ordem pública para quem vive no município.<br style="list-style: none;"><br style="list-style: none;"><span style="list-style: none; font-weight: bolder;">População aprova<br style="list-style: none;"><br style="list-style: none;"><img alt="" src="https://www.centronortenoticias.com.br/administracao/files/images/F1-Gov-Wanderlei%20Barbosa-entrega-chave-viatura-3BPM-Tupiratins-foto-Esequias%20Araujo.jpg" style="list-style: none; width: 800px; height: 457px;"></span><br style="list-style: none;"><br style="list-style: none;">A população das cidades de Itapiratins e Tupiratins compartilharam os mesmos sentimentos de gratidão ao governador Wanderlei Barbosa. O motivo foi a reativação da base do Destacamento da Polícia Militar (PM) em suas respectivas cidades, separadas pelo Rio Tocantins, na região centro norte do Estado.<br style="list-style: none;"><br style="list-style: none;">"É muito importante a reativação desse destacamento, porque até então estávamos sem apoio algum. Portanto somos gratos ao governador Wanderlei Barbosa pela atitude", comemorou a empresária Marcilene Fonseca de Sousa, de Tupiratins. Ja Valdeci Dias, também morador de Tupiratins, agradeceu ao Governo do Tocantins pela iniciativa e disse que a presença da polícia na cidade certamente vai colocar fim a sensação de insegurança e às arruaças de motoqueiros. "A presença da PM vai aumentar a sensação de segurança da população e coibir essas arruaças de motoqueiros. O sentimento é de gratidão ao Governador", disse.<br style="list-style: none;"><br style="list-style: none;">Por parte da comunidade de Itapiratins o sentimento também é de mais segurança e agradecimento ao Governo do Tocantins. O pequeno produtor rural, Manoel Resplande da Silva, afirma que esse destacamento era esperado há muito tempo. "Muito boa coisa, precisamos disso há muito tempo e graças ao governador Wanderlei agora chegou. Nossa cidade não é violenta, mas precisamos de policiamento para evitar coisa ruim", disse.<br style="list-style: none;"><br style="list-style: none;">Valmir Gomes de Sousa, ex-prefeito de Itapiratins, disse que a cidade tem mais de 3.500 habitantes e não contava com policiamento efetivo, o que de certa forma causava insegurança. "Faz muito tempo que estávamos esperando essa base. Foi uma excelente iniciativa do governador Wanderlei Barbosa, que teve essa sensibilidade de implantar o policiamento na nossa cidade e garantir o bem estar do povo", disse em tom de agradecimento<br style="list-style: none;"><br style="list-style: none;"><span style="list-style: none; font-weight: bolder;">Presenças</span><br style="list-style: none;">Acompanharam o governador Wanderlei Barbosa aos eventos em Tupiratins e Itapiratins, o deputado Leo Barbosa, secretários de Estado e outros auxiliares do Governo, além de prefeitos da região, vereadores e outras autoridades.&nbsp;(<em style="list-style: none;">Com informações de Jarbas Coutinho/Governo do Tocantin</em>s)<br style="list-style: none;"><br style="list-style: none;"><img alt="" src="https://www.centronortenoticias.com.br/administracao/files/images/M%C3%A1rcio.jpg" style="list-style: none; width: 800px; height: 533px;"><br style="list-style: none;"><br style="list-style: none;"><img alt="" src="https://www.centronortenoticias.com.br/administracao/files/images/Efetivo.jpg" style="list-style: none; width: 800px; height: 533px;"><br style="list-style: none;"><br style="list-style: none;"><img alt="" src="https://www.centronortenoticias.com.br/administracao/files/images/Destacamento%20Tupiratins.jpg" style="list-style: none; width: 800px; height: 533px;"><br style="list-style: none;"><br style="list-style: none;"><img alt="" src="https://www.centronortenoticias.com.br/administracao/files/images/Tirello.jpg" style="list-style: none; width: 800px; height: 533px;"><br style="list-style: none;">&nbsp;</p>&nbsp;</div>',
              attachment: null,
              model: null,
              url: null,
              status: 'P',
              open: 'N',
              start_date: '2023-02-16',
              end_date: '2050-12-31',
              tags: [
                '3º BPM',
                'DESTACAMENTOS',
                'ITAPIRATINS',
                'TUPIRATINS',
                'WANDERLEI BARBOSA',
                'CORONEL BARBOSA',
                'TENENTE-CORONEL TIRELLO',
                'SANDRO RODRIGUES',
                'FILÓ COELHLO',
                'SEGURANÇA PÚBLICA',
              ],
              bond: null,
              credits: 'Redação',
              note: null,
              published_at: '2023-02-16 10:20:00',
              slug: 'reabertura-dos-destacamentos-da-policia-militar-em-tupiratins-e-itapiratins-visam-garantia-da-segura-2',
              subtitle: null,
              created_at: '2023-02-16T13:30:18.000000Z',
              updated_at: '2023-02-16T13:30:44.000000Z',
              site_id: 13,
              code: null,
              page_id: 55,
              emphasis: 1,
              size_images_id: 1,
              endpoint: null,
            },
            {
              id: 136,
              type: 6,
              position: 1,
              image:
                'http://localhost:8080/storage/contents/xYHEN0Ao6aUSFxMhFtxF5Mk4ljMYqg4BXxY94ehV.jpg',
              title:
                'Polícia Militar prende mais um suspeito de participar de duplo homicídio em Recursolândia',
              descritive:
                '<p class="MsoNormal" style="text-align:justify"><span style="font-size:12.0pt;\r\nline-height:107%;font-family:&quot;Times New Roman&quot;,serif">Policiais do 3º Batalhão\r\nprenderam mais um suspeito de participar dos assassinatos de dois homens, de 21\r\ne 29 anos, em uma fazenda no município de Recursolândia, no início da noite do último\r\ndomingo, 12.<o:p></o:p></span></p><p class="MsoNormal" style="text-align:justify"><span style="font-size:12.0pt;\r\nline-height:107%;font-family:&quot;Times New Roman&quot;,serif">A prisão do homem de 64\r\nanos, que é avô do homem de 19 anos já custodiado por participação no delito, ocorreu\r\nna tarde desta terça-feira, 14, no centro de Recursolândia. Na sequência, a PM\r\nlocalizou, na casa dele, um revólver calibre .22, uma das armas supostamente\r\nusadas para matar as vítimas. &nbsp;<o:p></o:p></span></p><p class="MsoNormal" style="text-align:justify"><span style="font-size:12.0pt;\r\nline-height:107%;font-family:&quot;Times New Roman&quot;,serif">O idoso foi apresentado e\r\nautuado, em flagrante, pelo crime de posse irregular de arma de fogo de uso\r\npermitido na 50ª Delegacia de Polícia Civil em Pedro Afonso. <o:p></o:p></span></p><p class="MsoNormal" style="text-align:justify"><b><span style="font-size:12.0pt;line-height:107%;font-family:&quot;Times New Roman&quot;,serif"><b>Fora\r\nde circulação</b><o:p></o:p></span></b></p><p class="MsoNormal" style="text-align:justify"><span style="font-size:12.0pt;\r\nline-height:107%;font-family:&quot;Times New Roman&quot;,serif">Com a nova prisão chega a\r\ntrês o número de detidos envolvidos no duplo homicídio.<o:p></o:p></span></p><p class="MsoNormal" style="text-align:justify"><span style="font-size:12.0pt;\r\nline-height:107%;font-family:&quot;Times New Roman&quot;,serif">Ainda na segunda-feira,\r\n13, a Polícia Militar&nbsp; prendeu um homem\r\nde 19 anos e apreendeu um adolescente infrator de 16 anos de idade. Com a dupla\r\nforam localizadas duas espingardas artesanais calibre 20 e 30, peças para\r\nmontagem de uma espingarda e uma porção com 72 gramas de substância análoga à\r\nmaconha.&nbsp; <o:p></o:p></span></p><p class="MsoNormal" style="text-align:justify"><span style="font-size:12.0pt;\r\nline-height:107%;font-family:&quot;Times New Roman&quot;,serif">Na ocasião, os suspeitos,\r\nas armas e a droga foram apresentados pela guarnição do 3º BPM na Polícia Civil\r\nem Pedro Afonso, que realizou os procedimentos legais.<o:p></o:p></span></p><p>\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n</p><p class="MsoNormal" style="text-align:justify"><span style="font-size:12.0pt;\r\nline-height:107%;font-family:&quot;Times New Roman&quot;,serif">&nbsp;</span></p>',
              attachment: null,
              model: null,
              url: null,
              status: 'P',
              open: 'N',
              start_date: '2023-02-15',
              end_date: '2051-08-15',
              tags: ['segurança'],
              bond: null,
              credits: 'Redação',
              note: null,
              published_at: '2023-02-15 15:22:00',
              slug: 'policia-militar-prende-mais-um-suspeito-de-participar-de-duplo-homicidio-em-recursolandia-2',
              subtitle: null,
              created_at: '2023-02-15T18:24:18.000000Z',
              updated_at: '2023-02-16T18:01:36.000000Z',
              site_id: 13,
              code: null,
              page_id: 55,
              emphasis: 1,
              size_images_id: 1,
              endpoint: null,
            },
          ],
        },
        {
          id: 72,
          name: 'Versão Impressa',
          note: null,
          is_active: 1,
          order: 9,
          _lft: 77,
          _rgt: 78,
          parent_id: null,
          created_at: '2022-12-28T10:56:37.000000Z',
          updated_at: '2023-02-09T14:54:55.000000Z',
          site_id: 13,
          is_home: 1,
          order_home: 3,
          class: 'A',
          code: '8',
          home_start: 0,
          position: 'C',
          contents: [
            {
              id: 134,
              type: 5,
              position: 1,
              image:
                'http://localhost:8080/storage/contents/3TaDQnaZ3osZtQaLnAK9otcCVpffEWayS4Sy2u9I.png',
              title: 'VERSÃO IMPRESSA - Ano: 2022 - Edição: 153 - 23/12/2022',
              descritive: '<p><br></p>',
              attachment: null,
              model: null,
              url: 'https://drive.google.com/file/d/115zG7v09CqcGyCWiEb6uGfq6scq3paPb/view',
              status: 'P',
              open: 'M',
              start_date: '2023-02-09',
              end_date: '2070-12-31',
              tags: ['teste', 'versaoimpressa'],
              bond: null,
              credits: null,
              note: null,
              published_at: '2023-02-09 13:16:00',
              slug: 'versao-impressa-ano-2022-edicao-153-23122022',
              subtitle: null,
              created_at: '2023-02-09T16:17:08.000000Z',
              updated_at: '2023-02-10T00:17:24.000000Z',
              site_id: 13,
              code: null,
              page_id: 72,
              emphasis: 0,
              size_images_id: null,
              endpoint: null,
            },
            {
              id: 59,
              type: 5,
              position: 2,
              image:
                'http://localhost:8080/storage/contents/EDj4XUrsRO0CFezYoGrQnrcWBlkObrPQbOuouDdM.jpg',
              title: 'VERSÃO IMPRESSA - Ano: 2022 - Edição: 155 - 23/12/2022',
              descritive: '<p><br></p>',
              attachment: null,
              model: null,
              url: 'https://drive.google.com/file/d/1WjUSbBVOs3499zavQAYFUf1nokAbTZIO/view',
              status: 'P',
              open: 'M',
              start_date: '2022-12-23',
              end_date: '2023-12-31',
              tags: null,
              bond: null,
              credits: null,
              note: null,
              published_at: '2022-12-28 08:24:56',
              slug: 'versao-impressa-ano-2022-edicao-155-23122022',
              subtitle: null,
              created_at: '2022-12-28T11:05:37.000000Z',
              updated_at: '2023-02-09T14:53:55.000000Z',
              site_id: 13,
              code: null,
              page_id: 72,
              emphasis: 0,
              size_images_id: null,
              endpoint: null,
            },
            {
              id: 60,
              type: 5,
              position: 2,
              image:
                'http://localhost:8080/storage/contents/uxCGAjiPgiyHFkRsT5rwNWTyCj3iSL5jOEGEXu96.jpg',
              title: 'VERSÃO IMPRESSA - Ano: 2022 - Edição: 154 - 30/11/2022',
              descritive: '<p><br></p>',
              attachment: null,
              model: null,
              url: 'https://drive.google.com/file/d/115zG7v09CqcGyCWiEb6uGfq6scq3paPb/view',
              status: 'P',
              open: 'M',
              start_date: '2022-11-30',
              end_date: '2023-12-31',
              tags: null,
              bond: null,
              credits: null,
              note: null,
              published_at: '2022-12-28 08:22:09',
              slug: 'versao-impressa-ano-2022-edicao-154-30112023',
              subtitle: null,
              created_at: '2022-12-28T11:16:55.000000Z',
              updated_at: '2023-02-09T14:53:01.000000Z',
              site_id: 13,
              code: null,
              page_id: 72,
              emphasis: 0,
              size_images_id: null,
              endpoint: null,
            },
          ],
        },
      ],
      pages: [
        {
          id: 52,
          name: 'Cidade',
          note: null,
          is_active: 1,
          order: 1,
          _lft: 61,
          _rgt: 62,
          parent_id: null,
          created_at: '2022-12-19T17:41:37.000000Z',
          updated_at: '2023-02-09T12:15:10.000000Z',
          site_id: 13,
          is_home: 1,
          order_home: 1,
          class: 'A',
          code: '1',
          home_start: 0,
          position: 'C',
          children: [],
        },
        {
          id: 53,
          name: 'Política',
          note: null,
          is_active: 1,
          order: 2,
          _lft: 63,
          _rgt: 64,
          parent_id: null,
          created_at: '2022-12-19T17:42:03.000000Z',
          updated_at: '2023-02-09T12:16:07.000000Z',
          site_id: 13,
          is_home: 1,
          order_home: 3,
          class: 'A',
          code: '2',
          home_start: 0,
          position: 'C',
          children: [],
        },
        {
          id: 54,
          name: 'Economia',
          note: null,
          is_active: 1,
          order: 3,
          _lft: 65,
          _rgt: 66,
          parent_id: null,
          created_at: '2022-12-19T17:42:15.000000Z',
          updated_at: '2023-02-09T12:22:52.000000Z',
          site_id: 13,
          is_home: 1,
          order_home: 2,
          class: 'A',
          code: '3',
          home_start: 0,
          position: 'C',
          children: [],
        },
        {
          id: 55,
          name: 'Segurança',
          note: null,
          is_active: 1,
          order: 4,
          _lft: 67,
          _rgt: 68,
          parent_id: null,
          created_at: '2022-12-19T17:42:28.000000Z',
          updated_at: '2023-02-09T12:16:24.000000Z',
          site_id: 13,
          is_home: 1,
          order_home: 3,
          class: 'A',
          code: '4',
          home_start: 0,
          position: 'C',
          children: [],
        },
        {
          id: 64,
          name: 'Educação',
          note: null,
          is_active: 1,
          order: 5,
          _lft: 69,
          _rgt: 70,
          parent_id: null,
          created_at: '2022-12-20T14:46:20.000000Z',
          updated_at: '2023-02-09T12:22:09.000000Z',
          site_id: 13,
          is_home: 0,
          order_home: 1,
          class: 'A',
          code: '5',
          home_start: 0,
          position: 'C',
          children: [],
        },
        {
          id: 69,
          name: 'ASIDE',
          note: null,
          is_active: 1,
          order: 8,
          _lft: 75,
          _rgt: 76,
          parent_id: null,
          created_at: '2022-12-26T22:37:38.000000Z',
          updated_at: '2023-02-03T13:22:05.000000Z',
          site_id: 13,
          is_home: 0,
          order_home: null,
          class: 'A',
          code: '7',
          home_start: null,
          position: null,
          children: [],
        },
        {
          id: 72,
          name: 'Versão Impressa',
          note: null,
          is_active: 1,
          order: 9,
          _lft: 77,
          _rgt: 78,
          parent_id: null,
          created_at: '2022-12-28T10:56:37.000000Z',
          updated_at: '2023-02-09T14:54:55.000000Z',
          site_id: 13,
          is_home: 1,
          order_home: 3,
          class: 'A',
          code: '8',
          home_start: 0,
          position: 'C',
          children: [],
        },
      ],
      banners: [
        {
          id: 37,
          name: 'Teste de banner',
          image: 'https://placehold.co/1536x155',
          url: '<script async src="https://publicidade.to.gov.br/pub.js?code=wv8kDV0q" id="c-wv8kDV0q"></script>',
          is_active: 1,
          position: ['2'],
          type: 2,
          sequence: 1,
          created_at: '2023-02-16T20:43:05.000000Z',
          updated_at: '2023-02-16T20:51:19.000000Z',
          site_id: 13,
        },
      ],
    },
  };

  getHomePage(): Observable<Home> {
    return of(this.mockHome);
  }
}
